spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    hikari:
      pool-name: HikariConnPool
      maximum-pool-size: 30         # default: 10
      minimum-idle: 10              # default: same as max pool size
      connection-timeout: 30000     # default: 30s
      idle-timeout: 600000          # default: 10 minutes
      max-lifetime: 1800000         # default: 30 minutes
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

openapi:
  service:
    api-docs: account-service
    server: http://localhost:${server.port}
    title: Account service
    version: 1.0.0